name: lando-phpxdebug
services:
  xdebug:
    type: adeliom-php:8.1
    xdebug: "debug,develop"
  xdebug-on:
    type: adeliom-php:8.1
    xdebug: true
  xdebug-off:
    type: adeliom-php:8.1
    xdebug: false